using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using System.Runtime.InteropServices;
using Forms=System.Windows.Forms;

namespace QuickPanel {
 public class Program {
  static Mutex mutex;
  [STAThread] public static int Main(string[] args){try{if(args.Contains("--layout-test"))return InputLayoutTests.Run();if(args.Contains("--self-test"))return Tests.Run();if(args.Contains("--search-test"))return Tests.LiveSearch();if(args.Contains("--global-search-test"))return Tests.GlobalSearch();bool created;mutex=new Mutex(true,args.Contains("--smoke")?"Local\\QuickPanelSmoke":"Local\\QuickPanelPreviewV03",out created);if(!created){MessageBox.Show("快捷面板已运行，请使用 Alt+Space 或系统托盘打开。");return 0;}var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};var panel=new Panel(args.Contains("--smoke"));app.DispatcherUnhandledException+=(s,e)=>{if(args.Contains("--smoke")){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"smoke-error.txt"),e.Exception.ToString());app.Shutdown(2);}else MessageBox.Show("操作未完成："+e.Exception.Message,"快捷面板");e.Handled=true;};app.Run(panel.Window);mutex.ReleaseMutex();return 0;}catch(Exception e){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"startup-error.txt"),e.ToString());return 1;}}
 }
 public class Panel {
  public Window Window; TextBox search,working,translation; ListBox results; TextBlock status; FrameworkElement trPane,cmdPane; Settings settings;
  List<Entry> apps=new List<Entry>(); List<Entry> tools; CancellationTokenSource queryCts,translateCts; DispatcherTimer debounce; bool composing, smoke; int version; string language="简体中文"; Forms.NotifyIcon tray; IntPtr hwnd; bool hotkey; string mode="all";
  [DllImport("user32.dll")]static extern bool RegisterHotKey(IntPtr h,int id,uint mods,uint key);
  [DllImport("user32.dll")]static extern bool UnregisterHotKey(IntPtr h,int id);
  T Get<T>(string name)where T:class{return Window.FindName(name) as T;}
  public Panel(bool smokeMode){smoke=smokeMode;settings=smoke?new Settings():Store.Load();using(var stream=File.OpenRead(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Main.xaml")))Window=(Window)XamlReader.Load(stream);Window.MinWidth=640;Window.MinHeight=530;search=Get<TextBox>("Search");working=Get<TextBox>("WorkingDirectory");translation=Get<TextBox>("Translation");results=Get<ListBox>("Results");status=Get<TextBlock>("Status");trPane=Get<FrameworkElement>("TranslatePane");cmdPane=Get<FrameworkElement>("TerminalPane");working.Text=settings.Directory;
   tools=new List<Entry>{new Entry{Name="区域截图",Alias="jietu jt screenshot",Detail="框选区域 · 复制或保存 PNG",Kind="工具",Glyph="\uE722",Target="capture"},new Entry{Name="翻译",Alias="fanyi fy translate",Detail="输入 tr 文本，Ctrl+Enter 提交",Kind="工具",Glyph="\uE8C1",Target="translate"},new Entry{Name="终端命令",Alias="zhongduan zd terminal",Detail="在指定目录运行 Windows PowerShell 命令",Kind="工具",Glyph="\uE756",Target="terminal"},new Entry{Name="文件搜索",Alias="wenjian wj files",Detail="Everything · 输入 f 关键词",Kind="工具",Glyph="\uE8B7",Target="files"},new Entry{Name="设置",Alias="shezhi sz settings",Detail="配置 Everything 与翻译服务",Kind="工具",Glyph="\uE713",Target="settings"}};
   debounce=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(160)};debounce.Tick+=(s,e)=>{debounce.Stop();Refresh();};search.TextChanged+=(s,e)=>{version++;results.SelectedIndex=-1;translation.Clear();if(queryCts!=null)queryCts.Cancel();if(translateCts!=null)translateCts.Cancel();debounce.Stop();if(!composing)debounce.Start();};
   TextCompositionManager.AddPreviewTextInputStartHandler(search,(s,e)=>{composing=true;debounce.Stop();});TextCompositionManager.AddPreviewTextInputHandler(search,(s,e)=>{composing=false;debounce.Start();});
   Window.PreviewKeyDown+=Keys;results.MouseDoubleClick+=(s,e)=>Execute();
   Get<FrameworkElement>("TitleBar").MouseLeftButtonDown+=(s,e)=>{if(e.OriginalSource is TextBlock)Window.DragMove();};
   Click("AllButton",()=>SetInput(""));Click("FileButton",()=>SetInput("f "));Click("TranslateButton",()=>SetInput("tr "));Click("TerminalButton",()=>SetInput("> "));Click("CaptureButton",Capture);Click("SettingsButton",ShowSettings);Click("HideButton",()=>Window.Hide());Click("ExitButton",()=>Window.Hide());Click("RunCommand",Run);Click("SaveCommand",SaveCommand);Click("SubmitTranslation",async()=>await Translate());Click("CopyTranslation",()=>Copy(translation.Text));Click("ChineseButton",()=>SetLanguage("简体中文"));Click("EnglishButton",()=>SetLanguage("英语"));
   Window.SourceInitialized+=(s,e)=>{hwnd=new WindowInteropHelper(Window).Handle;if(!smoke){hotkey=RegisterHotKey(hwnd,1,0x4001,0x20);HwndSource.FromHwnd(hwnd).AddHook(Hook);if(!hotkey)status.Text="Alt+Space 注册失败，可使用托盘打开。";}};
   Window.Closing+=(s,e)=>{if(tray!=null)tray.Dispose();if(hotkey)UnregisterHotKey(hwnd,1);};Window.Closed+=(s,e)=>Application.Current.Shutdown();Window.Loaded+=async(s,e)=>{if(smoke){await Smoke();return;}InitTray();status.Text="正在读取开始菜单应用…";apps=await Task.Run(()=>Services.Apps());Refresh();if(!String.IsNullOrEmpty(Store.Warning))status.Text=Store.Warning;search.Focus();};
  }
  void Click(string name,Action action){Get<Button>(name).Click+=(s,e)=>Safe(action);}
  void Safe(Action action){try{action();}catch(Exception e){status.Text=e.Message;}}
  void SetLanguage(string s){language=s;if(translateCts!=null)translateCts.Cancel();translation.Clear();Get<Button>("ChineseButton").Content="简体中文"+(s=="简体中文"?" ✓":"");Get<Button>("EnglishButton").Content="英语"+(s=="英语"?" ✓":"");}
  IntPtr Hook(IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled){if(msg==0x312&&w.ToInt32()==1){Show();handled=true;}return IntPtr.Zero;}
  void InitTray(){tray=new Forms.NotifyIcon{Icon=System.Drawing.SystemIcons.Application,Text="快捷面板 · Alt+Space",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("打开",null,(s,e)=>Window.Dispatcher.Invoke(new Action(Show)));menu.Items.Add("设置",null,(s,e)=>Window.Dispatcher.Invoke(new Action(()=>{Show();ShowSettings();})));menu.Items.Add("退出",null,(s,e)=>Window.Dispatcher.Invoke(new Action(Quit)));tray.ContextMenuStrip=menu;tray.DoubleClick+=(s,e)=>Window.Dispatcher.Invoke(new Action(Show));}
  void Show(){Window.Show();Window.WindowState=WindowState.Normal;Window.Activate();search.Focus();}
  void Quit(){SearchRuntime.Stop();if(queryCts!=null)queryCts.Cancel();if(translateCts!=null)translateCts.Cancel();if(tray!=null){tray.Visible=false;tray.Dispose();tray=null;}if(hotkey)UnregisterHotKey(hwnd,1);Window.Close();Application.Current.Shutdown();}
  void SetInput(string s){search.Text=s;search.CaretIndex=s.Length;search.Focus();Refresh();}
  public static string Mode(string s){return s.StartsWith("f ",StringComparison.OrdinalIgnoreCase)?"files":s.StartsWith("tr ",StringComparison.OrdinalIgnoreCase)?"translate":s.StartsWith("> ")?"command":"all";}
  async void Refresh(){mode=Mode(search.Text);foreach(var pair in new[]{new[]{"AllButton","all"},new[]{"FileButton","files"},new[]{"TranslateButton","translate"},new[]{"TerminalButton","command"}}){Get<Button>(pair[0]).BorderBrush=new SolidColorBrush(pair[1]==mode?Color.FromRgb(85,214,190):Colors.Transparent);}trPane.Visibility=mode=="translate"?Visibility.Visible:Visibility.Collapsed;cmdPane.Visibility=mode=="command"?Visibility.Visible:Visibility.Collapsed;results.Visibility=mode=="all"||mode=="files"?Visibility.Visible:Visibility.Collapsed;
   if(mode=="translate"){status.Text="Ctrl+Enter 提交翻译 · 仅发送当前输入文本";return;}if(mode=="command"){status.Text="普通权限执行 · 请确认命令与工作目录";return;}
   if(mode=="files"){int request=version;var text=search.Text.Substring(2).Trim();if(queryCts!=null)queryCts.Cancel();queryCts=new CancellationTokenSource();var token=queryCts.Token;results.ItemsSource=null;if(text.Length==0){status.Text="输入文件名或 Everything 搜索语法，例如 ext:pdf 合同";return;}status.Text="正在查询 Everything…首次全盘索引可能需要几分钟";try{var found=await Services.Files(settings,text,token,message=>{if(request==version&&!token.IsCancellationRequested)status.Text=message;});if(request!=version||token.IsCancellationRequested)return;Bind(found);status.Text=found.Count==0?"没有匹配文件。":"显示前 "+found.Count+" 项 · Tab 展开文件操作";}catch(OperationCanceledException){}catch(Exception e){if(request==version)status.Text=e.Message;}return;}
   string q=search.Text.Trim();var web=WebSearch.Match(q);if(web!=null){Bind(new List<Entry>{web});status.Text=web.Target==null?"输入关键词和搜索内容，例如 bd 26年新能源车推荐":"按 Enter 在默认浏览器打开搜索结果";return;}var all=apps.Concat(tools).Concat(settings.Commands.Select(c=>new Entry{Name=c.Name,Detail=c.Directory+"  ·  "+c.Command,Kind="命令",Glyph="\uE756",Target=c.Directory,Command=c.Command,Alias=Services.Initials(c.Name)}));var matched=all.Select(e=>new{Item=e,Rank=Services.Rank(e,q)}).Where(e=>e.Rank>0).OrderByDescending(e=>e.Rank).ThenBy(e=>e.Item.Name).Take(60).Select(e=>e.Item).ToList();if(q.Length==0)matched=tools.Concat(apps.Take(8)).ToList();Bind(matched);status.Text=matched.Count==0?"没有匹配应用。搜索文件请点击“文件”或输入 f 。":"已发现 "+apps.Count+" 个开始菜单应用 · 支持名称和常用汉字首字母";if(!hotkey&&!smoke)status.Text+=" · 快捷键不可用，请使用托盘";
  }
  void Bind(List<Entry> list){string old=(results.SelectedItem as Entry)==null?null:((Entry)results.SelectedItem).Target;results.ItemsSource=list;results.SelectedItem=list.FirstOrDefault(e=>e.Target==old)??list.FirstOrDefault();}
  async void Keys(object sender,KeyEventArgs e){if(composing||e.Key==Key.ImeProcessed)return;var current=Mode(search.Text);if(e.Key==Key.Escape){if(current!="all")SetInput("");else Window.Hide();e.Handled=true;return;}if(e.Key==Key.Enter){if(current=="translate"){if((Keyboard.Modifiers&ModifierKeys.Control)!=0){await Translate();e.Handled=true;}}else if(current=="command"){if(e.OriginalSource==search){Safe(Run);e.Handled=true;}}else if(e.OriginalSource==search||results.IsKeyboardFocusWithin){Safe(Execute);e.Handled=true;}return;}
   if(results.Visibility==Visibility.Visible&&(e.OriginalSource==search||results.IsKeyboardFocusWithin)){if(e.Key==Key.Down||e.Key==Key.Up){results.SelectedIndex=Math.Max(0,Math.Min(results.Items.Count-1,results.SelectedIndex+(e.Key==Key.Down?1:-1)));if(results.SelectedItem!=null)results.ScrollIntoView(results.SelectedItem);e.Handled=true;}if(e.Key==Key.Tab&&Keyboard.Modifiers==ModifierKeys.None){Actions();e.Handled=true;}}
  }
  void Execute(){var item=results.SelectedItem as Entry;if(item==null)return;if(item.Kind=="网页"&&item.Target==null){status.Text="请在关键词后输入搜索内容。";search.Focus();return;}if(item.Kind=="工具"){switch(item.Target){case "capture":Capture();break;case "translate":SetInput("tr ");break;case "terminal":SetInput("> ");break;case "files":SetInput("f ");break;case "settings":ShowSettings();break;}return;}if(item.Kind=="命令"){working.Text=item.Target;SetInput("> "+item.Command);return;}Services.Open(item.Target);Window.Hide();}
  void Actions(){var item=results.SelectedItem as Entry;if(item==null)return;var menu=new ContextMenu{Background=new SolidColorBrush(Color.FromRgb(34,38,44)),Foreground=Brushes.White};AddMenu(menu,"打开",Execute);if(item.Kind=="文件"||item.Kind=="应用"){AddMenu(menu,"复制路径",()=>Copy(item.Target));AddMenu(menu,"打开所在位置",()=>{if(!File.Exists(item.Target)&&!Directory.Exists(item.Target))throw new IOException("此路径已不存在。");System.Diagnostics.Process.Start("explorer.exe","/select,"+Services.Quote(item.Target));});if(item.Folder){AddMenu(menu,"在此打开终端",()=>{Services.Terminal("",item.Target);Window.Hide();});AddMenu(menu,"在此运行命令",()=>{working.Text=item.Target;SetInput("> ");});}}menu.PlacementTarget=results;menu.Closed+=(s,e)=>search.Focus();menu.IsOpen=true;((MenuItem)menu.Items[0]).Focus();}
  void AddMenu(ContextMenu m,string name,Action a){var i=new MenuItem{Header=name};i.Click+=(s,e)=>Safe(a);m.Items.Add(i);}
  void Copy(string text){if(String.IsNullOrEmpty(text))return;Clipboard.SetText(text);status.Text="已复制到剪贴板。";}
  void Run(){if(Mode(search.Text)!="command")return;string command=search.Text.Substring(2);if(String.IsNullOrWhiteSpace(command)){status.Text="请先输入命令。";return;}Services.Terminal(command,working.Text);Window.Hide();}
  void SaveCommand(){if(Mode(search.Text)!="command"||String.IsNullOrWhiteSpace(search.Text.Substring(2)))return;var input=new TextBox{Text=search.Text.Substring(2),Margin=new Thickness(0,10,0,14)};var dialog=Dialog("收藏命令",440,240);var stack=(StackPanel)((ContentControl)dialog.Tag).Content;stack.Children.Add(new TextBlock{Text="名称（搜索此名称即可再次使用）"});stack.Children.Add(input);var save=Button("保存",()=>{if(String.IsNullOrWhiteSpace(input.Text))return;settings.Commands.Add(new SavedCommand{Name=input.Text.Trim(),Command=search.Text.Substring(2),Directory=working.Text});Store.Save(settings);dialog.Close();status.Text="已收藏命令。";});stack.Children.Add(save);dialog.ShowDialog();}
  async Task Translate(){if(Mode(search.Text)!="translate")return;string text=search.Text.Substring(3).Trim();if(text.Length==0){status.Text="请在 tr 后输入要翻译的文字。";return;}if(translateCts!=null)translateCts.Cancel();var local=new CancellationTokenSource();translateCts=local;int request=version;string target=language;translation.Clear();status.Text="正在翻译…";try{string result=await Services.Translate(settings,text,target,local.Token);if(!local.IsCancellationRequested&&request==version){translation.Text=result;status.Text="翻译完成。";}}catch(OperationCanceledException){if(request==version&&translateCts==local)status.Text="请求已取消或超时，可重试。";}catch(Exception e){if(request==version&&translateCts==local)status.Text=e.Message;}}
  void Capture(){Window.Hide();var delay=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};delay.Tick+=(s,e)=>{delay.Stop();try{var capture=new CaptureWindow();capture.ShowDialog();}catch(Exception ex){Show();status.Text="截图失败："+ex.Message;}};delay.Start();}
  Window Dialog(string title,double width,double height){return DialogChrome.Create(Window,title,width,height);}
  Button Button(string label,Action action){var b=new Button{Content=label,HorizontalAlignment=HorizontalAlignment.Left,Margin=new Thickness(0,8,0,0)};b.Click+=(s,e)=>{try{action();}catch(Exception ex){MessageBox.Show(ex.Message,"快捷面板");}};return b;}
  void ShowSettings(){
   var dialog=Dialog("快捷面板 · 设置",810,640);var layout=new Grid{Margin=new Thickness(18)};layout.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(145)});layout.ColumnDefinitions.Add(new ColumnDefinition());((ContentControl)dialog.Tag).Content=layout;
   var nav=new StackPanel{Margin=new Thickness(0,10,18,0)};layout.Children.Add(nav);var right=new DockPanel{Margin=new Thickness(10,0,0,0)};Grid.SetColumn(right,1);layout.Children.Add(right);
   var save=Button("保存设置",()=>{});DockPanel.SetDock(save,Dock.Bottom);right.Children.Add(save);var pages=new Grid();right.Children.Add(pages);
   var navButtons=new System.Collections.Generic.Dictionary<string,Button>();var forms=new System.Collections.Generic.Dictionary<string,StackPanel>();foreach(var name in new[]{"常规","快捷键","文件搜索","翻译","终端"}){var pane=new StackPanel{Visibility=Visibility.Collapsed};forms[name]=pane;var scroller=new ScrollViewer{Content=pane,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};scroller.SetBinding(UIElement.VisibilityProperty,new System.Windows.Data.Binding("Visibility"){Source=pane});pages.Children.Add(scroller);var button=Button(name,()=>{foreach(var pair in forms)pair.Value.Visibility=pair.Key==name?Visibility.Visible:Visibility.Collapsed;foreach(var pair in navButtons){pair.Value.Background=pair.Key==name?new SolidColorBrush(Color.FromRgb(33,54,56)):Brushes.Transparent;pair.Value.BorderBrush=pair.Key==name?new SolidColorBrush(Color.FromRgb(85,214,190)):Brushes.Transparent;}});navButtons[name]=button;button.HorizontalAlignment=HorizontalAlignment.Stretch;button.Background=Brushes.Transparent;button.BorderBrush=Brushes.Transparent;nav.Children.Add(button);pane.Children.Add(new TextBlock{Text=name,FontSize=23,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,20)});}
   Action<StackPanel,string> label=(pane,text)=>pane.Children.Add(new TextBlock{Text=text,Foreground=new SolidColorBrush(Color.FromRgb(169,175,186)),Margin=new Thickness(0,12,0,8),TextWrapping=TextWrapping.Wrap});
   label(forms["常规"],"快捷面板 0.3.3 · 本地优先");label(forms["常规"],"无需账号。关闭主窗口后保留在托盘；右键托盘选择退出。不自动设置开机启动。");label(forms["常规"],"系统工具现已内置：控制面板、记事本、计算器、画图、任务管理器、命令提示符。支持中文名称、英文名称和拼音别名。");
   label(forms["快捷键"],"Alt + Space　唤起主面板");label(forms["快捷键"],"↑ / ↓　选择结果\nEnter　打开选中项目\nTab　展开操作\nEsc　返回或隐藏\nCtrl + Enter　提交翻译");label(forms["快捷键"],"自定义全局快捷键尚未开放。若 Alt+Space 被其他应用占用，可从托盘打开。");
   label(forms["文件搜索"],"● 官方 Everything 与 CLI 已内置");label(forms["文件搜索"],SearchRuntime.ScopeDescription);label(forms["文件搜索"],"自动识别组件路径。优先连接已运行的标准 Everything；否则索引所有已就绪的本地磁盘，包括固定磁盘和移动磁盘。");forms["文件搜索"].Children.Add(Button("打开 Everything",()=>SearchRuntime.Options()));label(forms["文件搜索"],"无需管理员的全盘扫描首次建索引可能较慢；未完成前请稍候。只能搜索当前账户有权读取的路径。网络共享不自动扫描。");
   var es=new TextBox{Text=settings.EsPath??""};var advanced=new StackPanel();advanced.Children.Add(es);advanced.Children.Add(Button("选择其他 es.exe",()=>{var picker=new Microsoft.Win32.OpenFileDialog{Filter="Everything CLI|es.exe"};if(picker.ShowDialog(dialog)==true)es.Text=picker.FileName;}));forms["文件搜索"].Children.Add(new Expander{Header="高级：手动覆盖 CLI 路径（通常无需修改）",Content=advanced,Margin=new Thickness(0,16,0,0)});
   label(forms["翻译"],"完整 HTTPS 接口地址（Chat Completions 兼容）");var endpoint=new TextBox{Text=settings.Endpoint??""};forms["翻译"].Children.Add(endpoint);label(forms["翻译"],"模型名称");var model=new TextBox{Text=settings.Model??""};forms["翻译"].Children.Add(model);label(forms["翻译"],"API Key（留空保留已有密钥）");var key=new PasswordBox();forms["翻译"].Children.Add(key);label(forms["翻译"],"仅主动提交时发送文字。密钥使用 Windows 当前用户加密保存，不提供内置云端额度。");forms["翻译"].Children.Add(Button("清除已有密钥",()=>{settings.ProtectedKey="";Store.Save(settings);key.Clear();MessageBox.Show("已清除本机密钥。");}));
   label(forms["终端"],"执行环境：Windows PowerShell · 普通权限");label(forms["终端"],"默认工作目录");var directory=new TextBox{Text=settings.Directory};forms["终端"].Children.Add(directory);label(forms["终端"],"命令在独立终端运行。从文件夹进入时使用选中的目录。收藏命令会先载入，仍需主动执行。");
   save.Click+=(s,e)=>{try{Uri u;if(endpoint.Text.Length>0&&(!Uri.TryCreate(endpoint.Text,UriKind.Absolute,out u)||u.Scheme!="https"))throw new IOException("翻译地址必须为 HTTPS。");if(es.Text.Length>0&&(!File.Exists(es.Text)||!String.Equals(Path.GetFileName(es.Text),"es.exe",StringComparison.OrdinalIgnoreCase)))throw new IOException("CLI 路径无效。");if(!Directory.Exists(directory.Text))throw new IOException("工作目录不存在。");var protectedKey=key.Password.Length>0?Store.Protect(key.Password):settings.ProtectedKey;settings.EsPath=es.Text;settings.Endpoint=endpoint.Text;settings.Model=model.Text;settings.Directory=directory.Text;settings.ProtectedKey=protectedKey;Store.Save(settings);working.Text=settings.Directory;dialog.Close();Refresh();}catch(Exception ex){MessageBox.Show(ex.Message,"设置未保存");}};
   forms["文件搜索"].Visibility=Visibility.Visible;navButtons["文件搜索"].Background=new SolidColorBrush(Color.FromRgb(33,54,56));navButtons["文件搜索"].BorderBrush=new SolidColorBrush(Color.FromRgb(85,214,190));if(smoke){var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(200)};timer.Tick+=(s,e)=>{timer.Stop();if(dialog.WindowStyle!=WindowStyle.None||!dialog.AllowsTransparency||dialog.ResizeMode!=ResizeMode.NoResize)throw new Exception("Dialog retained native chrome");SaveWindow(dialog,"preview-settings.png");dialog.Close();};dialog.Loaded+=(s,e)=>timer.Start();}dialog.ShowDialog();
  }

  async Task Smoke(){apps=new List<Entry>{new Entry{Name="微信",Detail=@"C:\Program Files\Tencent\WeChat\WeChat.exe",Kind="应用",Glyph="\uE8A5",Target="demo",Alias="wx"}};SetInput("微信");await Task.Delay(250);SaveRender("preview-apps.png");working.Text=@"D:\Projects\demo";SetInput("> git status");await Task.Delay(250);SaveRender("preview-terminal.png");SetInput("tr Keep things simple.");translation.Text="让事情保持简单。\n（仅视觉测试样例）";await Task.Delay(250);SaveRender("preview-translation.png");SetInput("bd 26年新能源车推荐");await Task.Delay(250);SaveRender("preview-web-search.png");ShowSettings();File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"smoke-result.txt"),"WPF loaded; application / command / translation / settings views rendered; settings has no native chrome. No external command, network or clipboard action performed.");Quit();}
  void SaveRender(string name){SaveWindow(Window,name);}
  void SaveWindow(Window target,string name){target.UpdateLayout();var bitmap=new RenderTargetBitmap((int)target.ActualWidth,(int)target.ActualHeight,96,96,PixelFormats.Pbgra32);bitmap.Render(target);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,name)))encoder.Save(f);}
 }
}
